spring:
  application:
    name: Api-Gateway
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          # Enables the DiscoveryClientRouteDefinitionLocator, which automatically
          # creates routes based on services registered in Eureka.
          # Example: A service named 'USER-SERVICE' will automatically get a route
          # at /user-service/**
          enabled: true
          #lower-case-service-id: true
server:
  port: ${PORT:8087}


#service:
#  auth:
#    name: USER-SERVICE
#    url: ${SERVICES_USER-SERVICE:http://USER-SERVICE}



eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${server.port}

# Logging for debugging
logging:
  level:
    # Increases log verbosity for troubleshooting discovery and routing issues.
    com.netflix.discovery: DEBUG
    com.budget.b.lite: DEBUG # Assuming 'com.budget.b.lite' is a custom package
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG

