

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://trolley.proxy.rlwy.net:47143/railway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ASDTMxskShzhAAskArtUcabreagvzssG}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: user-service
            client-secret: sHE4P6Ayr4EwUF4E1LTQmjuiuBGJQmO6
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/tripTrekker
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/tripTrekker

keycloak:
  server-url: http://localhost:8081
  realm: tripTrekker
  admin:
    realm: master
    username: admin
    password: admin123
    client-id: admin-cli

server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
